vscode:
  extensions:
    - vscjava.vscode-java-pack@0.8.1:LRImBn//d5JhH4PUEI1BaQ==
    - sohibe.java-generate-setters-getters@4.2.2:TGDLfj6/6KwENqC9dWEGyQ==
    - Pivotal.vscode-spring-boot@1.14.0:ZPqd7ysDHfq8h05jD/me8g==